WebMVC/Models/ContactViewModel.cs
namespace WebMVC.Models
{

    public class ContactViewModel
    {

        public int Id { get; set; }

        public String Name { get; set; }

        public String Email { get; set; }

        public String Address { get; set; }


        public ContactViewModel()
        {

        }

        public ContactViewModel(int id, String name, String email, String address)
        {

            Id = id;
            Name = name;
            Email = email;
            Address = address;
        }

    }
}

WebMVC/Models/ErrorViewModel.cs
namespace WebMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebMVC/Models/ProductViewModel.cs
namespace WebMVC.Models;

public class ProductViewModel
{

    public int Id { get; set; }
    public String Name { get; set; }
    public String Category { get; set; }
    public int Price { get; set; }

    public ProductViewModel()
    {
    }

    public ProductViewModel(int id, String name, String category, int price)
    {
        Id = id;
        Name = name;
        Category = category;
        Price = price;
    }

}

WebMVC/Controllers/BlogController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }

}

WebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebMVC/Controllers/ProductController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Collections.Generic;
using WebMVC.Models;
using System.Threading.Tasks;


namespace WebMVC.ProductController
{
    public class ProductController : Controller
    {

        private static List<ProductViewModel> _productViewModels = new List<ProductViewModel>(){

            new ProductViewModel(1, "Jus Durian", "Minuman", 10000),
            new ProductViewModel(2, "Jus Mangga", "Minuman", 8000),
            new ProductViewModel(3, "Jus Semangka", "Minuman", 10000),

        };

        public IActionResult Index()
        {

            return View(_productViewModels);


        }

        public IActionResult AddProduct()
        {
            // Menampilkan halamaan tambah product
            return View();
        }

        [HttpPost]
        public IActionResult Save(int id, [Bind("Id, Name, Category, Price")] ProductViewModel product)
        {

            _productViewModels.Add(product);
            return Redirect("Index");

        }

        // Update Product
        public IActionResult EditProduct(int? id)
        {
            // Menampilkan halaman edit product
            ProductViewModel product = _productViewModels.Find(x => x.Id.Equals(id));
            return View(product);
        }

        // Proses Update product

        public IActionResult UpdateProduct(int id, [Bind("Id, Name, Category, Price")] ProductViewModel product)
        {

            // Pertama menghapus data lama
            ProductViewModel productOld = _productViewModels.Find(x => x.Id.Equals(id));
            _productViewModels.Remove(productOld);

            // Menambahkan data baru
            _productViewModels.Add(product);
            return Redirect("Index");

        }


        public IActionResult Delete(int? id)
        {

            // find data yang akan dihapus
            ProductViewModel product = _productViewModels.Find(x => x.Id.Equals(id));


            // Delete product 
            _productViewModels.Remove(product);
            return View(product);

        }


        public IActionResult Details(int? id)
        {

            // find menggunakan Linq
            ProductViewModel product = (from p in _productViewModels
                                        where p.Id.Equals(id)
                                        select p).SingleOrDefault(new ProductViewModel());

            return View(product);

        }


    }
}

WebMVC/Controllers/ServicesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{

    public class ServicesController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

    }

}

WebMVC/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Blog Post";
}

<div class="text-center">
    <h1 class="display-4">Welcome Blog Post</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMVC/Views/Contact/Index.cshtml
@model List<ContactViewModel>
@{
    ViewData["Title"] = "User Contact";
}

<div class="container-fluid">
    <h1 class="display-4">User Contact</h1>
    <div class="row d-flex justify-content-around">
        <div class="col-lg-12">
            @foreach(var user in Model){
                <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="https://konsultanpendidikan.com/wp-content/uploads/2014/10/susanwojcicki.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@user.Name</h5>
                        <p class="card-text">@user.Address</p>
                    <a href="#" class="btn btn-primary">@user.Email</a>
                </div>
            </div>
            }
        </div>
    </div>
</div>

WebMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="text-center">
    <h1 class="display-4">About</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Conatact";
}
<h1>@ViewData["Title"]</h1>

<p>Contact US</p>

WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMVC/Views/Product/AddProduct.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Add Product";
}

<h2> Form Add Product</a>
<form asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="Id">Product Id</label>
        <input asp-for="Id" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Name">Product Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Category">Product Category</label>
        <input asp-for="Category" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Price">Product Price</label>
        <input asp-for="Price" class="form-control">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>

</form>


@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

WebMVC/Views/Product/Details.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Product Details";
}

<h2>Product Detail</h2>
<table class="table tab-content">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
    <tr>
        <th>Product Name</th>
        <td>@Model.Name</td>
    </tr>
    
    <tr>
        <th>Category</th>
        <td>@Model.Category</td>
    </tr>
    <tr>
            <th>Price</th>
            <td>@Model.Price</td>
    </tr>
    <tr>
            <a asp-action="EditProduct" asp-route-id="@Model.Id" class="btn btn-sm btn-warning m-2">Edit</a>
            <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-sm btn-danger">Delete</a>
    </tr>
    </tbody>
</table>

WebMVC/Views/Product/EditProduct.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Edit Product";
}

<h2> Form Edit Product</a>
<form asp-action="UpdateProduct" method="post">
    <div class="form-group">
        <label asp-for="Id">Product Id</label>
        <input asp-for="Id" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Name">Product Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Category">Product Category</label>
        <input asp-for="Category" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Price">Product Price</label>
        <input asp-for="Price" class="form-control">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>

</form>


@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

WebMVC/Views/Product/Index.cshtml
@model List<ProductViewModel>

@{
    ViewData["Title"] = "Product";
}

<h2>Product List<h2>
<a asp-action="AddProduct" asp-route-id="" class="btn btn-sm btn-primary">Add Product</a>
<table class="table table-responsive">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Category</td>
            <td>Price</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Category</td>
                <td>@item.Price</td>
                <td>
                    <a asp-action="EditProduct" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebMVC/Views/Services/Index.cshtml
@{
    ViewData["Title"] = "Services";
}

<div class="text-center">
    <h1 class="display-4">Services</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">AddProduct</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>